env:
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
jobs:
  verify-staged-with-samples:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Samples Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        repository: spring-projects/spring-integration-samples
        show-progress: false
    - continue-on-error: true
      name: Set up Gradle
      uses: spring-io/spring-gradle-build-action@v2
    - continue-on-error: true
      name: Prepare Samples project against Staging
      run: "printf \"allprojects {\n        repositories {\n          maven { \n \
        \           url 'https://repo.spring.io/libs-staging-local'\n            credentials\
        \ {\n              username = '$ARTIFACTORY_USERNAME'\n              password\
        \ = '$ARTIFACTORY_PASSWORD'\n            }\n          }\n        }\n     \
        \ }\" > staging-repo-init.gradle\n\nsed -i \"1,/springIntegrationVersion.*/s/springIntegrationVersion.*/springIntegrationVersion='${{\
        \ inputs.releaseVersion }}'/\" build.gradle  \n"
    - continue-on-error: true
      name: Verify Spring Integration Samples against staged release
      run: gradle check --init-script staging-repo-init.gradle
name: Verify Staged Artifacts
on:
  repository_dispatch:
    types: trigger-ga___verify-staged-artifacts.yml
